name: benzene_vqe_adaptvqe
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - qiskit=0.44
  - qiskit-nature=0.6
  - matplotlib=3.7
  - numpy=1.24
  - pyscf=2.2
  - pip
  - pip:
    - qiskit-aer==0.13
    - qiskit-ibmq-provider==0.20
